### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pthomson** [GBSEcom/paymentjs-integration-nodejs#1]
when I run this example (and the other paymentjs example) I always get the following result posted to my webhook. 

{
"error": true,
"gatewayReason":
{
"code": 403,
"message": "HMAC validation Failure"
},
"gatewayRefId": "",
"reason": "UNKNOWN,
"zeroDollarAuth": false
​}

**Comment by brandon-garcia** [comment]
That is most likely an issue with your gateway credentials or a misconfiguration on the gateway side.
The error is occurring in the request sent by the PaymentJS backend to the gateway api.

**Comment by pthomson** [comment]
thank you for the reply! (and for the new, easier to follow example!). I have been struggling with this for a while and just this morning was able to escalate with Merchant Services and they did confirm they most likely have a misconfiguration on their side.  Closing this issue based on the new information.

**Comment by brandon-garcia** [comment]
glad to hear!
