### ISSUE TITLE
Pass some metadata in session-authorize which paymentJS will return in webhook

### ISSUE THREAD

**Issue by kashifgrocerkey** [GBSEcom/paymentjs-integration-nodejs#9]
Hi,

Is there a way while calling POST /authorize-session then we also pass some metadata and that metadata will be returned in webhook?

I have a requirement where we need that metadata compulsory in webhook so thinking if there is a way of doing it in Payeezy PaymentJS flow.

Regards,
Kashif

**Comment by brandon-garcia** [comment]
The Nonce header sent during authorize session is returned on the response as well as the webhook call, you can use that header to include the metadata

**Comment by kashifgrocerkey** [comment]
Thanks alot @brandon-garcia , it really works for me :)
